language: python
matrix:
  include:
    - python: 3.7
    dist: xenial

services:
  - docker

before_script: pip install docker_compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
